Fix compilation with xcode 16.3
xcode 16.3 ships with clang17 as default compiler.
This version of clang warns about casts between incompatible function types,
and v8 has some of those:
```
include/node/v8-persistent-handle.h:512:26: error: cast from 'typename WeakCallbackInfo<ObjectWrap>::Callback' (aka 'void (*)(const WeakCallbackInfo<ObjectWrap> &)') to 'Callback' (aka 'void (*)(const WeakCallbackInfo<void> &)') converts to incompatible function type [-Werror,-Wcast-function-type-mismatch]
```

This commit adds a -Wno-cast-function-type-mismatch flag to the compiler
flags to suppress these warnings (that would otherwise cause errors because
of the -Werror flag) and also a -Wno-unknown-warning-option flag to suppress
the warning about the unknown warning option "-Wcast-function-type-mismatch"
for clang < 17.